spring.application.name=backend

spring.datasource.url=jdbc:h2:file:./data/cineflix
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

tmdb.api-key=857d4f6329b16b5de4eba8deb063df8c
tmdb.base-url=https://api.themoviedb.org/3

jwt.secret=8f7K2mP9xL4qR6vT1zN5cB3wY7hJ0sD8kP4mX9qL2vR7tN5c
jwt.expiration=3600000